### PR TITLE
Fixes #4, Enable Hive metastore metrics

### LINKED ISSUE #4: Enable Hive Metastore metrics
_As a SysOps_
_I want to enable Hive Metastore metrics_
_So that process health can be monitored_

**Acceptance Criteria:**
* Hive metastore emits metrics to a file

### PR DESCRIPTION
**Pull request by pradeepbhadani**
@ExpediaInc/apiary-committers

### CODE REVIEW

**Comment by pradeepbhadani** [comment]
@rpoluri As perhttps://cwiki.apache.org/confluence/display/Hive/Configuration+Properties#ConfigurationProperties-Metrics, metrics can be exposed using `JSON_FILE` or `JMX`

**Comment by rpoluri** [comment]
In current versions 1.3.0, 2.x, metrics only supports built in reporters.

In hive 3.0, this is extended so that we can assign custom reporter class using "hive.service.metrics.codahale.reporter.classes"
https://cwiki.apache.org/confluence/display/Hive/Configuration+Properties#ConfigurationProperties-hive.metastore.metrics.enabled
https://issues.apache.org/jira/browse/HIVE-16206

wtih current version we need to override complete metrics implementation using "hive.service.metrics.class", which seems far more complex. 
If this is not urgent I suggest to wait till hive 3.0 shows up in EMR.

**Comment by pradeepbhadani** [comment]
@rpoluri  If we can get at-least JVM heap usage somehow that would help and then we may be able to delay on this.

**Comment by pradeepbhadani** [comment]
Will raise new PR when we agree on the process for metrics

**Pull request closed without merging**
